umu.aadd.segundum.modelo.Usuario=umu.aadd.segundum.repositorio.RepositorioUsuariosJPA
umu.aadd.segundum.modelo.Producto=umu.aadd.segundum.repositorio.RepositorioProductosJPA
umu.aadd.segundum.modelo.Categoria=umu.aadd.segundum.repositorio.RepositorioCategoriasJPA