segundum.modelo.Usuario=segundum.repositorio.RepositorioUsuariosJPA
segundum.modelo.Producto=segundum.repositorio.RepositorioProductosJPA
segundum.modelo.Categoria=segundum.repositorio.RepositorioCategoriasJPA