umu.aadd.segundum.servicio.IServicioUsuarios=umu.aadd.segundum.servicio.ServicioUsuarios
umu.aadd.segundum.servicio.IServicioProductos=umu.aadd.segundum.servicio.ServicioProductos
umu.aadd.segundum.servicio.IServicioCategorias=umu.aadd.segundum.servicio.ServicioCategorias