segundum.servicio.IServicioUsuarios=segundum.servicio.ServicioUsuarios
segundum.servicio.IServicioProductos=segundum.servicio.ServicioProductos
segundum.servicio.IServicioCategorias=segundum.servicio.ServicioCategorias